[application]

# App (Project) Name
name = "fraction-concoction"

# Dioxus App Default Platform
# web, desktop, fullstack
default_platform = "web"

# `build` & `serve` dist path
out_dir = "docs"

# resource (assets) file folder
asset_dir = "assets"

[web.app]
base_path = "fraction-concoction"

# HTML title tag content
title = "fraction-concoction"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
