[application]

[web.app]
base_path = "fraction-concoction"

# HTML title tag content
title = "fraction-concoction"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
