[application]

# `build` & `serve` dist path
platform = "web"

[web.wasm_opt]
level = "z"
debug = false
keep_names = false
memory_packing = true
extra_features = ["--converge"]

[web]
pre_compress = true
resource_strategy = "aggressive"

[web.app]
base_path = "fraction-concoction"

# HTML title tag content
title = "Fraction Concoction"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
